import { File } from "lucide-react";

export const teamMembers = [
  "Field Officer Ramesh",
  "PA Srinivas",
  "Engineer Kumar",
  "Officer Priya",
  "Officer Anil",
  "Officer Suresh",
  "Officer Lakshmi",
  "Officer Raju",
  "Officer Meena",
  "Officer Vijay",
];

export const mockGrievances = [
  {
    id: 1,
    trackingNumber: "GRI-I-23-08012025",
    title: "Road Repair Needed",
    category: "Infrastructure",
    status: "Pending",
    priority: "High",
    createdOn: "01-09-2025",
    completedOn: "",
    pendingSince: "9 days",
    citizenName: "Rajesh Kumar",
    citizenPhone: "+91-9876543210",
    location: "Manthanani Village",
    district: "Karimnagar",
    constituency: "Manthanani",
    description: "Main road has multiple potholes",
    assignedTo: "Field Officer Ramesh",
  },
  {
    id: 2,
    trackingNumber: "GRI-H-45-07012025",
    title: "Water Supply Issue",
    category: "Water",
    status: "In Progress",
    priority: "Medium",
    createdOn: "01-08-2025",
    completedOn: "",
    pendingSince: "30 days",
    citizenName: "Sita Devi",
    citizenPhone: "+91-9876543211",
    location: "Ramagundam",
    district: "Peddapalli",
    constituency: "Ramagundam",
    description: "Irregular water supply",
    assignedTo: "PA Srinivas",
  },
  {
    id: 3,
    trackingNumber: "GRI-H-46-08012025",
    title: "Street Light Not Working",
    category: "Electricity",
    status: "Pending",
    priority: "Low",
    createdOn: "03-08-2025",
    completedOn: "",
    pendingSince: "7 days",
    citizenName: "Mohammed Ali",
    citizenPhone: "+91-9876543212",
    location: "Karimnagar Town",
    district: "Karimnagar",
    constituency: "Karimnagar Urban",
    description: "Street lights not working in the area",
    assignedTo: "Officer Priya",
  },
  {
    id: 4,
    trackingNumber: "GRI-I-47-08012025",
    title: "Drainage Blockage",
    category: "Sanitation",
    status: "In Progress",
    priority: "High",
    createdOn: "02-08-2025",
    completedOn: "",
    pendingSince: "10 days",
    citizenName: "Sunil Sharma",
    citizenPhone: "+91-9876543213",
    location: "Warangal City",
    district: "Warangal",
    constituency: "Warangal East",
    description: "Sewage water overflowing in streets",
    assignedTo: "Officer Anil",
  },
  {
    id: 5,
    trackingNumber: "GRI-I-48-08012025",
    title: "Garbage Collection Delay",
    category: "Sanitation",
    status: "Pending",
    priority: "Medium",
    createdOn: "04-08-2025",
    completedOn: "",
    pendingSince: "5 days",
    citizenName: "Anita Reddy",
    citizenPhone: "+91-9876543214",
    location: "Mancherial",
    district: "Mancherial",
    constituency: "Mancherial",
    description: "Garbage collection irregular",
    assignedTo: "Officer Suresh",
  },
  {
    id: 6,
    trackingNumber: "GRI-I-49-08012025",
    title: "Hospital Staff Shortage",
    category: "Health",
    status: "Pending",
    priority: "High",
    createdOn: "05-08-2025",
    completedOn: "",
    pendingSince: "4 days",
    citizenName: "Ravi Teja",
    citizenPhone: "+91-9876543215",
    location: "Nizamabad",
    district: "Nizamabad",
    constituency: "Nizamabad Rural",
    description: "Shortage of doctors in local PHC",
    assignedTo: "Officer Lakshmi",
  },
  {
    id: 7,
    trackingNumber: "GRI-I-50-08012025",
    title: "Park Maintenance Needed",
    category: "Recreation",
    status: "In Progress",
    priority: "Low",
    createdOn: "06-08-2025",
    completedOn: "",
    pendingSince: "3 days",
    citizenName: "Prakash Rao",
    citizenPhone: "+91-9876543216",
    location: "Sircilla",
    district: "Rajanna Sircilla",
    constituency: "Sircilla",
    description: "Children park maintenance pending",
    assignedTo: "Officer Raju",
  },
  {
    id: 8,
    trackingNumber: "GRI-I-51-08012025",
    title: "Electricity Transformer Fault",
    category: "Electricity",
    status: "Pending",
    priority: "High",
    createdOn: "07-08-2025",
    completedOn: "",
    pendingSince: "2 days",
    citizenName: "Deepa Singh",
    citizenPhone: "+91-9876543217",
    location: "Jagtial",
    district: "Jagtial",
    constituency: "Jagtial",
    description: "Transformer sparks and power cuts",
    assignedTo: "Officer Meena",
  },
  {
    id: 9,
    trackingNumber: "GRI-I-52-08012025",
    title: "School Infrastructure",
    category: "Education",
    status: "Pending",
    priority: "Medium",
    createdOn: "08-08-2025",
    completedOn: "",
    pendingSince: "1 day",
    citizenName: "Arjun Verma",
    citizenPhone: "+91-9876543218",
    location: "Adilabad",
    district: "Adilabad",
    constituency: "Adilabad Urban",
    description: "Need benches and fans in classrooms",
    assignedTo: "Officer Vijay",
  },
  {
    id: 10,
    trackingNumber: "GRI-I-53-08012025",
    title: "Bus Shelter Required",
    category: "Transport",
    status: "In Progress",
    priority: "Low",
    createdOn: "01-08-2025",
    completedOn: "",
    pendingSince: "12 days",
    citizenName: "Sneha Gupta",
    citizenPhone: "+91-9876543219",
    location: "Nirmal",
    district: "Nirmal",
    constituency: "Nirmal",
    description: "No shelter at main bus stop",
    assignedTo: "Field Officer Ramesh",
  },
];

export const mockProjects = [
  {
    id: 1,
    projectNumber: "PRJ-I-12-08012025",
    name: "Bridge Construction",
    category: "Infrastructure",
    status: "In Progress",
    projectValue: "₹0.5 Crore",
    amountPaid: "₹0.2 Crore",
    comission: "₹0.01 Crore",
    startedOn: "01-09-2025",
    completedOn: "",
    location: "Manthanani",
    district: "Karimnagar",
    constituency: "Manthanani",
    description: "New bridge construction",
    assignedTo: "Engineer Kumar",
    pdfIcon: File,
  },
  {
    id: 2,
    projectNumber: "PRJ-H-13-08012025",
    name: "Hospital Renovation",
    category: "Health",
    status: "Pending",
    projectValue: "₹1.2 Crore",
    amountPaid: "₹0.3 Crore",
    comission: "₹0.02 Crore",
    startedOn: "05-08-2025",
    completedOn: "",
    location: "Nizamabad",
    district: "Nizamabad",
    constituency: "Nizamabad Rural",
    description: "Renovation of district hospital",
    assignedTo: "Officer Lakshmi",
    pdfIcon: File,
  },
  {
    id: 3,
    projectNumber: "PRJ-I-14-08012025",
    name: "Drainage System Upgrade",
    category: "Sanitation",
    status: "In Progress",
    projectValue: "₹0.8 Crore",
    amountPaid: "₹0.5 Crore",
    comission: "₹0.03 Crore",
    startedOn: "10-08-2025",
    completedOn: "",
    location: "Warangal City",
    district: "Warangal",
    constituency: "Warangal East",
    description: "Modern underground drainage system",
    assignedTo: "Officer Anil",
    pdfIcon: File,
  },
  {
    id: 4,
    projectNumber: "PRJ-I-15-08012025",
    name: "Water Tank Construction",
    category: "Water",
    status: "Pending",
    projectValue: "₹0.6 Crore",
    amountPaid: "₹0.1 Crore",
    comission: "₹0.01 Crore",
    startedOn: "12-08-2025",
    completedOn: "",
    location: "Ramagundam",
    district: "Peddapalli",
    constituency: "Ramagundam",
    description: "Overhead water tank",
    assignedTo: "PA Srinivas",
    pdfIcon: File,
  },
  {
    id: 5,
    projectNumber: "PRJ-I-16-08012025",
    name: "School Building Extension",
    category: "Education",
    status: "Pending",
    projectValue: "₹0.9 Crore",
    amountPaid: "₹0.4 Crore",
    comission: "₹0.02 Crore",
    startedOn: "15-08-2025",
    completedOn: "",
    location: "Adilabad",
    district: "Adilabad",
    constituency: "Adilabad Urban",
    description: "Adding new classrooms and labs",
    assignedTo: "Officer Vijay",
    pdfIcon: File,
  },
  {
    id: 6,
    projectNumber: "PRJ-I-17-08012025",
    name: "Park Development",
    category: "Recreation",
    status: "In Progress",
    projectValue: "₹0.4 Crore",
    amountPaid: "₹0.2 Crore",
    comission: "₹0.01 Crore",
    startedOn: "18-08-2025",
    completedOn: "",
    location: "Sircilla",
    district: "Rajanna Sircilla",
    constituency: "Sircilla",
    description: "Beautification and play area development",
    assignedTo: "Officer Raju",
    pdfIcon: File,
  },
  {
    id: 7,
    projectNumber: "PRJ-I-18-08012025",
    name: "Transformer Installation",
    category: "Electricity",
    status: "Pending",
    projectValue: "₹0.3 Crore",
    amountPaid: "₹0.1 Crore",
    comission: "₹0.005 Crore",
    startedOn: "20-08-2025",
    completedOn: "",
    location: "Jagtial",
    district: "Jagtial",
    constituency: "Jagtial",
    description: "New transformer installation",
    assignedTo: "Officer Meena",
    pdfIcon: File,
  },
  {
    id: 8,
    projectNumber: "PRJ-I-19-08012025",
    name: "Bus Terminal Upgrade",
    category: "Transport",
    status: "Pending",
    projectValue: "₹1.5 Crore",
    amountPaid: "₹0.6 Crore",
    comission: "₹0.04 Crore",
    startedOn: "22-08-2025",
    completedOn: "",
    location: "Nirmal",
    district: "Nirmal",
    constituency: "Nirmal",
    description: "Expansion of bus terminal",
    assignedTo: "Field Officer Ramesh",
    pdfIcon: File,
  },
  {
    id: 9,
    projectNumber: "PRJ-I-20-08012025",
    name: "Community Hall Construction",
    category: "Infrastructure",
    status: "In Progress",
    projectValue: "₹0.7 Crore",
    amountPaid: "₹0.3 Crore",
    comission: "₹0.02 Crore",
    startedOn: "25-08-2025",
    completedOn: "",
    location: "Mancherial",
    district: "Mancherial",
    constituency: "Mancherial",
    description: "New hall for community events",
    assignedTo: "Officer Suresh",
    pdfIcon: File,
  },
  {
    id: 10,
    projectNumber: "PRJ-I-21-08012025",
    name: "Solar Street Lights",
    category: "Electricity",
    status: "Pending",
    projectValue: "₹0.5 Crore",
    amountPaid: "₹0.2 Crore",
    comission: "₹0.01 Crore",
    startedOn: "28-08-2025",
    completedOn: "",
    location: "Karimnagar",
    district: "Karimnagar",
    constituency: "Karimnagar Urban",
    description: "Solar powered street lights installation",
    assignedTo: "Officer Priya",
    pdfIcon: File,
  },
];
